export type FilmTest = {
    name: string;
    year: number;
    genre: string[];
    info: string;
};

//these dummymovies were generated by ChatGpt

export const dummyMovies: FilmTest[] = [
    {
        name: "Inception",
        year: 2010,
        genre: ["Sci-Fi", "Thriller"],
        info: "A thief who enters the dreams of others to steal secrets is given a chance to have his criminal history erased.",
    },
    {
        name: "The Dark Knight",
        year: 2008,
        genre: ["Action", "Crime", "Drama"],
        info: "Batman battles the Joker, a criminal mastermind who seeks to create chaos in Gotham City.",
    },
    {
        name: "Interstellar",
        year: 2014,
        genre: ["Sci-Fi", "Adventure", "Drama"],
        info: "A team of explorers travels through a wormhole in space to save humanity.",
    },
    {
        name: "Pulp Fiction",
        year: 1994,
        genre: ["Crime", "Drama"],
        info: "The lives of two hitmen, a boxer, a gangster's wife, and a pair of robbers intertwine in four tales of violence and redemption.",
    },
    {
        name: "Fight Club",
        year: 1999,
        genre: ["Drama", "Thriller"],
        info: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much bigger.",
    },
    {
        name: "The Matrix",
        year: 1999,
        genre: ["Sci-Fi", "Action", "Adventure"],
        info: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    },
    {
        name: "The Shawshank Redemption",
        year: 1994,
        genre: ["Drama"],
        info: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    },
    {
        name: "The Godfather",
        year: 1972,
        genre: ["Crime", "Drama"],
        info: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    },
    {
        name: "Forrest Gump",
        year: 1994,
        genre: ["Drama", "Romance"],
        info: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary childhood.",
    },
    {
        name: "The Avengers",
        year: 2012,
        genre: ["Action", "Adventure", "Sci-Fi"],
        info: "Earth's mightiest heroes must come together and learn to fight as a team to stop Loki and his alien army from enslaving humanity.",
    },
    {
        name: "Toy Story",
        year: 1995,
        genre: ["Animation", "Adventure", "Comedy"],
        info: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    },
    {
        name: "The Princess Bride",
        year: 1987,
        genre: ["Adventure", "Comedy", "Fantasy"],
        info: "A farm boy turned pirate sets out to rescue his true love from an arranged marriage to a prince.",
    },
];
